'use client';
import {useState} from 'react';
import {Compass,Map,CalendarDays,Wallet,Flag,Settings,Download,ArrowRight,TrainFront,Utensils,Mountain,Check} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import tour from '@/data/tour.json';

function Landscape(){return <svg className="china-landscape" viewBox="0 0 720 570" role="img" aria-label="Стилизованные горы Китая и круг солнца"><defs><linearGradient id="mist" x2="0" y2="1"><stop stopColor="#e4dcc7"/><stop offset="1" stopColor="#f5efdf"/></linearGradient></defs><circle cx="474" cy="157" r="106" fill="#a3352c" opacity=".92"/><path d="M0 430 80 250 145 320 207 165 260 277 314 90 363 270 419 209 480 342 547 221 602 390 720 256V570H0Z" fill="#bec4b3"/><path d="M0 475 76 351 124 400 193 284 246 412 309 234 372 424 422 359 484 456 573 336 635 470 720 391V570H0Z" fill="#5a7467"/><path d="M0 526 107 438 181 494 267 382 340 512 453 433 544 532 633 454 720 505V570H0Z" fill="#234e43"/><path d="M0 490Q180 462 320 492T720 475V570H0Z" fill="url(#mist)" opacity=".58"/><path d="M534 390h116l-58-27Zm12 11h92v51h-92Zm-16 60h125l-63-29Z" fill="#283f34"/><path d="M583 408h18v30h-18Z" fill="#d5ad60"/><path d="M65 520q150-50 320 0t335-4" stroke="#f5efdf" strokeWidth="12" fill="none" opacity=".7"/></svg>}

export default function TourOverview({exportBackup,onImport,message}:{exportBackup:()=>void;onImport:(text:string)=>void;message:string}){
 const [tab,setTab]=useState('route');
 return <main className="trip china-tour"><header><a className="brand" href="/"><span className="china-seal" aria-hidden="true">中</span><b>Китай <em>2026</em></b></a><span className="family-label">Чэнду · Чжанцзяцзе · Чэнду</span><span className="china-header-note">Вылет 26 октября</span></header>
 <Tabs value={tab} onValueChange={v=>setTab(String(v))}><div className="topbar"><TabsList variant="line"><TabsTrigger value="route"><Map/>Маршрут</TabsTrigger><TabsTrigger value="schedule"><CalendarDays/>По дням</TabsTrigger><TabsTrigger value="budget"><Wallet/>Бюджет</TabsTrigger><TabsTrigger value="checklist"><Flag/>Подготовка</TabsTrigger><TabsTrigger value="settings"><Settings/>Мой план</TabsTrigger></TabsList><span className="import-date">Роман и Артур · школьный класс</span></div>
 <TabsContent value="route"><section className="china-hero"><div className="china-hero-copy"><p className="china-eyebrow">中国 · ПУТЕШЕСТВИЕ В КИТАЙ</p><h1>Там, где горы<br/>касаются <em>неба.</em></h1><p className="china-lead">От чайных переулков Чэнду до туманных вершин Чжанцзяцзе. Панды, древние храмы и восемь дней новых впечатлений.</p><button className="primary" onClick={()=>setTab('schedule')}>Открыть программу <ArrowRight size={18}/></button><div className="china-facts"><div><b>08</b><span>дней в программе</span></div><div><b>02</b><span>города</span></div><div><TrainFront size={27}/><span>скоростные поезда</span></div></div></div><div className="china-art"><Landscape/><span className="china-art-label">山水<br/><small>ГОРЫ И ВОДЫ</small></span></div></section><section className="china-section"><div className="china-section-heading"><p className="china-eyebrow">ПУТЬ ЧЕРЕЗ СЫЧУАНЬ И ХУНАНЬ</p><h2>Два города. Один большой мир.</h2></div><div className="china-city-grid"><article><span className="china-city-index">01 / 成都</span><h3>Чэнду</h3><p>Панды и храмы, книжные лабиринты, хотпот и вечерняя Сычуаньская опера.</p><span>Дни 1–3 и 7–8</span></article><article><span className="china-city-index">02 / 张家界</span><h3>Чжанцзяцзе</h3><p>Стеклянный мост, пещера Жёлтого дракона, озеро Баофэн и Небесные врата.</p><span>Дни 3–7</span></article></div></section></TabsContent>
 <TabsContent value="schedule"><section className="china-section"><p className="china-eyebrow">ВОСЕМЬ ГЛАВ ПУТЕШЕСТВИЯ</p><h1 className="china-page-title">Каждый день — новая история.</h1><p className="china-disclaimer">Вылет — 26 октября 2026. Дата прилёта и календарные даты программы ещё не подтверждены. Время рейсов и поездов приведено из предложения туроператора и требует подтверждения.</p><div className="china-days">{tour.days.map(d=><article className="china-day" key={d.day}><div className="china-day-number"><span>ДЕНЬ</span><b>{String(d.day).padStart(2,'0')}</b></div><div><div className="china-day-meta"><span>{d.city}</span><span>{d.theme}</span></div><h2>{d.title}</h2><ul>{d.items.map(item=><li key={item}>{item}</li>)}</ul><p className="china-meals"><Utensils size={15}/>{d.meals}</p></div></article>)}</div></section></TabsContent>
 <TabsContent value="budget"><section className="china-section"><p className="china-eyebrow">ПРЕДЛОЖЕНИЕ ТУРОПЕРАТОРА</p><h1 className="china-page-title">Путешествие в цифрах.</h1><p className="china-disclaimer">Цены из PDF, за одного человека. Оплата в рублях по курсу туроператора. Международный перелёт оплачивается отдельно; итог поездки и оплаченные суммы пока не известны.</p><div className="china-price-grid">{tour.prices.map(p=><article key={p.label}><p>{p.label}</p><strong>${p.amount.toLocaleString('ru-RU')}</strong><span>USD / человек</span></article>)}</div><div className="china-info-grid"><article><h2>Включено в тур</h2><ul>{tour.included.map(s=><li key={s}><Check size={16}/>{s}</li>)}</ul></article><article><h2>Дополнительно</h2><p>Международные авиаперелёты не включены.</p><p>Курс оплаты, условия отмены и личные расходы уточняются. Расходы на месте будем учитывать в юанях.</p></article></div><h2 className="china-subtitle">Отели из предложения</h2><div className="china-hotels">{tour.hotels.map(h=><p key={h}>{h}</p>)}</div><p className="china-disclaimer">Распределение отелей по ночам и бронирование не подтверждены.</p></section></TabsContent>
 <TabsContent value="checklist"><section className="china-section"><p className="china-eyebrow">ДО НАЧАЛА ПУТЕШЕСТВИЯ</p><h1 className="china-page-title">Уточним главное.</h1><p className="china-disclaimer">Вопросы для завершения плана и подтверждения программы.</p><div className="china-questions">{tour.questions.map((q,i)=><article key={q}><span>{String(i+1).padStart(2,'0')}</span><p>{q}</p></article>)}</div></section></TabsContent>
 <TabsContent value="settings"><section className="china-section"><p className="china-eyebrow">ПЛАН ПОД РУКОЙ</p><h1 className="china-page-title">Наше путешествие, наш темп.</h1><p className="china-disclaimer">От семьи едут Роман и Артур, вместе со школьным классом Артура. Вылет — 26 октября 2026. Программа тура пока не привязана к дате прилёта. После добавления календарного маршрута будут доступны карта, статусы посещений, личные заметки и расходы. Личные правки сохраняются в этом браузере.</p><div className="china-info-grid"><article><h2>Резервная копия</h2><p>Сохраните основу календарного плана для дальнейшего заполнения.</p><button className="secondary" onClick={exportBackup}><Download size={17}/>Сохранить план</button></article><article><h2>Импорт маршрута</h2><label>Файл маршрута JSON<input type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2000000){onImport('');return;}onImport(await f.text());e.target.value='';}}/></label></article></div>{message&&<p className="notice" role="status">{message}</p>}</section></TabsContent>
 </Tabs><footer><Compass size={20}/><span>Китай 2026 · Наше путешествие</span><span>made with ♥ by Roman A. Proskurnin</span></footer></main>;
}
