'use client';
import {useState,lazy,Suspense} from 'react';
import DayPlaces from './tour-day-places';
import TourIntro from './tour-intro';
import TourCalendar from './tour-calendar';
import {tourDate,type TourDay} from '@/lib/tour-route';
const TourMap=lazy(()=>import('./tour-map'));
import {Compass,Map,CalendarDays,Wallet,Flag,Settings,Download,ArrowRight,TrainFront,Utensils,Mountain,Check} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import tour from '@/data/tour.json';
import './tour-visuals.css';

export default function TourOverview({exportBackup,onImport,message}:{exportBackup:()=>void;onImport:(text:string)=>void;message:string}){
 const [tab,setTab]=useState('route');
 const [selectedDay,setSelectedDay]=useState<TourDay>('all');
 const selectDay=(day:TourDay)=>setSelectedDay(day);
 return <main className="trip china-tour"><header><a className="brand" href="/"><span className="china-seal" aria-hidden="true">中</span><b>Китай <em>2026</em></b></a><span className="family-label">Чэнду · Чжанцзяцзе · Чэнду</span><span className="china-header-note">26 октября — 2 ноября</span></header>
 <Tabs value={tab} onValueChange={v=>setTab(String(v))}><div className="topbar"><TabsList variant="line"><TabsTrigger value="route"><Map/>Маршрут</TabsTrigger><TabsTrigger value="schedule"><CalendarDays/>По дням</TabsTrigger><TabsTrigger value="budget"><Wallet/>Бюджет</TabsTrigger><TabsTrigger value="checklist"><Flag/>Подготовка</TabsTrigger><TabsTrigger value="settings"><Settings/>Мой план</TabsTrigger></TabsList><span className="import-date">Роман и Артур · школьный класс</span></div>
 {(tab==='route'||tab==='schedule')&&<TourIntro onProgram={()=>{setTab('schedule');setSelectedDay('all');requestAnimationFrame(()=>document.getElementById('tour-days')?.scrollIntoView({behavior:'smooth',block:'start'}));}}/>}
 {(tab==='route'||tab==='schedule')&&<TourCalendar selectedDay={selectedDay} onDay={selectDay}/>}
 <TabsContent value="route"><Suspense fallback={<div className="china-section">Разворачиваем карту…</div>}><TourMap day={selectedDay} onDay={selectDay}/></Suspense><section className="china-section"><div className="china-section-heading"><p className="china-eyebrow">ПУТЬ ЧЕРЕЗ СЫЧУАНЬ И ХУНАНЬ</p><h2>Два города. Один большой мир.</h2></div><div className="china-city-grid"><article><span className="china-city-index">01 / 成都</span><h3>Чэнду</h3><p>Панды и храмы, книжные лабиринты, хотпот и вечерняя Сычуаньская опера.</p><span>26–28 октября · 1–2 ноября</span></article><article><span className="china-city-index">02 / 张家界</span><h3>Чжанцзяцзе</h3><p>Стеклянный мост, пещера Жёлтого дракона, озеро Баофэн и Небесные врата.</p><span>28 октября — 1 ноября</span></article></div></section></TabsContent>
 <TabsContent value="schedule"><section id="tour-days" className="china-section"><p className="china-eyebrow">ВОСЕМЬ ГЛАВ ПУТЕШЕСТВИЯ</p><h1 className="china-page-title">Каждый день — новая история.</h1><p className="china-disclaimer">Даты поездки: 26 октября — 2 ноября 2026. Вылет и возвращение — Шереметьево. Дни программы предварительно распределены с 26 октября по 2 ноября; привязку уточним после подтверждения времени прилёта. Время рейсов и поездов приведено из предложения туроператора и требует подтверждения.</p><div className="china-days">{(selectedDay==='all'||selectedDay==='departure'||selectedDay===1)&&<article className="china-day"><div className="china-day-number"><span>ОКТЯБРЬ</span><b>26</b></div><div><div className="china-day-meta"><span>Вылет в Китай</span></div><h2>Начало путешествия</h2><p>26 октября 2026 года · Шереметьево → Чэнду. Время вылета и аэропорт прибытия уточняются.</p></div></article>}{tour.days.filter(d=>selectedDay==='all'||selectedDay===d.day).map(d=><article className="china-day" key={d.day}><div className="china-day-number"><span>ДЕНЬ</span><b>{String(d.day).padStart(2,'0')}</b></div><div><div className="china-day-meta"><span>{tourDate(d.day)} 2026</span><span>{d.city}</span><span>{d.theme}</span></div><h2>{d.title}</h2><DayPlaces day={d.day} onMap={()=>{setSelectedDay(d.day);setTab('route');requestAnimationFrame(()=>document.getElementById('tour-calendar')?.scrollIntoView({behavior:'smooth',block:'start'}));}}/><h3 className="tour-program-heading">Программа дня</h3><ul>{d.items.map(item=><li key={item}>{item}</li>)}</ul><p className="china-meals"><Utensils size={15}/>{d.meals}</p></div></article>)}{(selectedDay==='all'||selectedDay==='return'||selectedDay===8)&&<article className="china-day"><div className="china-day-number"><span>НОЯБРЬ</span><b>02</b></div><div><div className="china-day-meta"><span>Возвращение в Москву</span></div><h2>Домой — с новыми историями</h2><p>2 ноября 2026 года · Чэнду → Шереметьево. Время и аэропорт вылета уточняются.</p></div></article>}</div></section></TabsContent>
 <TabsContent value="budget"><section className="china-section"><p className="china-eyebrow">ПРЕДЛОЖЕНИЕ ТУРОПЕРАТОРА</p><h1 className="china-page-title">Путешествие в цифрах.</h1><p className="china-disclaimer">Цены из PDF, за одного человека. Оплата в рублях по курсу туроператора. Международный перелёт оплачивается отдельно; итог поездки и оплаченные суммы пока не известны.</p><div className="china-price-grid">{tour.prices.map(p=><article key={p.label}><p>{p.label}</p><strong>${p.amount.toLocaleString('ru-RU')}</strong><span>USD / человек</span></article>)}</div><div className="china-info-grid"><article><h2>Включено в тур</h2><ul>{tour.included.map(s=><li key={s}><Check size={16}/>{s}</li>)}</ul></article><article><h2>Дополнительно</h2><p>Международные авиаперелёты не включены.</p><p>Курс оплаты, условия отмены и личные расходы уточняются. Расходы на месте будем учитывать в юанях.</p></article></div><h2 className="china-subtitle">Отели из предложения</h2><div className="china-hotels">{tour.hotels.map(h=><p key={h}>{h}</p>)}</div><p className="china-disclaimer">Распределение отелей по ночам и бронирование не подтверждены.</p></section></TabsContent>
 <TabsContent value="checklist"><section className="china-section"><p className="china-eyebrow">ДО НАЧАЛА ПУТЕШЕСТВИЯ</p><h1 className="china-page-title">Уточним главное.</h1><p className="china-disclaimer">Вопросы для завершения плана и подтверждения программы.</p><div className="china-questions">{tour.questions.map((q,i)=><article key={q}><span>{String(i+1).padStart(2,'0')}</span><p>{q}</p></article>)}</div></section></TabsContent>
 <TabsContent value="settings"><section className="china-section"><p className="china-eyebrow">ПЛАН ПОД РУКОЙ</p><h1 className="china-page-title">Наше путешествие, наш темп.</h1><p className="china-disclaimer">От семьи едут Роман и Артур, вместе со школьным классом Артура. Поездка — с 26 октября по 2 ноября 2026, вылет и возвращение в Шереметьево. Карта и фотографии уже доступны; календарные даты экскурсий, личные заметки и расходы дополним после подтверждения программы. Личные правки сохраняются в этом браузере.</p><div className="china-info-grid"><article><h2>Резервная копия</h2><p>Сохраните основу календарного плана для дальнейшего заполнения.</p><button className="secondary" onClick={exportBackup}><Download size={17}/>Сохранить план</button></article><article><h2>Импорт маршрута</h2><label>Файл маршрута JSON<input type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2000000){onImport('');return;}onImport(await f.text());e.target.value='';}}/></label></article></div>{message&&<p className="notice" role="status">{message}</p>}</section></TabsContent>
 </Tabs><footer><Compass size={20}/><span>Китай 2026 · Наше путешествие</span><span>made with ♥ by Roman A. Proskurnin</span></footer></main>;
}
