'use client';
import {useState,useEffect,lazy,Suspense} from 'react';
import {api,type User} from '@/lib/account-client';
import './account/account.css';
import DayPlaces,{PlacePhoto} from './tour-day-places';
import TourGallery from './tour-gallery';
import places from '@/data/tour-places.json';
import TourIntro from './tour-intro';
import TourCalendar from './tour-calendar';
import TourCountdown from './tour-countdown';
import PackingList,{type PrivateTour} from './tour-packing';
import {tourDate,type TourDay} from '@/lib/tour-route';
const TourMap=lazy(()=>import('./tour-map'));
import {Compass,Map,CalendarDays,Wallet,Flag,Settings,Download,ArrowRight,TrainFront,Utensils,Mountain,Check} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import tour from '@/data/public-tour.json';
import './tour-visuals.css';
import './tour-polish.css';

export default function TourOverview({exportBackup,onImport,message}:{exportBackup:()=>void;onImport:(text:string)=>void;message:string}){
 const [user,setUser]=useState<User|null>(null),[accountLoading,setAccountLoading]=useState(true),[accountError,setAccountError]=useState('');
 const [privateTour,setPrivateTour]=useState<PrivateTour|null>(null);
 useEffect(()=>{let active=true;let generation=0;const refresh=async()=>{const run=++generation;const current=()=>active&&run===generation;try{const {user}=await api<{user:User|null}>('/api/account/me');if(!current())return;setUser(user);setPrivateTour(null);if(user&&user.role!=='viewer'){const data=await api<PrivateTour>('/api/trip/tour');if(current())setPrivateTour(data);}if(current())setAccountError('');}catch{if(current()){setUser(null);setPrivateTour(null);setAccountError('Сервис входа временно недоступен.');}}finally{if(current())setAccountLoading(false);}};refresh();window.addEventListener('focus',refresh);return()=>{active=false;window.removeEventListener('focus',refresh);};},[]);
 const accessMessage=<section className="china-section"><h1 className="china-page-title">Доступ для участников</h1><p>{accountLoading?'Проверяем доступ…':accountError||'Бюджет и подготовка доступны владельцу и участникам поездки.'}</p><a className="account-menu-link" href="/account/">{user?'Мой аккаунт':'Войти на сайт'}</a></section>;
 const [tab,setTab]=useState('route');
 const [selectedDay,setSelectedDay]=useState<TourDay>('all');
 const selectDay=(day:TourDay)=>setSelectedDay(day);
 return <main className="trip china-tour"><header><a className="brand" href="/"><span className="china-seal" aria-hidden="true">中</span><b>Китай <em>2026</em></b></a><span className="family-label">Чэнду · Чжанцзяцзе · Чэнду</span><span className="china-header-note">26 октября — 2 ноября</span><a className="account-menu-link" href="/account/">{user?user.name||'Мой аккаунт':'Войти'}</a></header>
 <Tabs value={tab} onValueChange={v=>{setTab(String(v));if(v==='schedule')setSelectedDay(d=>d==='departure'?1:d==='return'?8:d);}}><div className="topbar"><TabsList variant="line"><TabsTrigger value="route"><Map/>Маршрут</TabsTrigger><TabsTrigger value="schedule"><CalendarDays/>По дням</TabsTrigger><TabsTrigger value="budget"><Wallet/>Бюджет</TabsTrigger><TabsTrigger value="checklist"><Flag/>Подготовка</TabsTrigger><TabsTrigger value="settings"><Settings/>Мой план</TabsTrigger></TabsList><span className="import-date">Роман и Артур · школьный класс</span></div>
 {tab==='route'&&<TourIntro onProgram={()=>{setTab('schedule');setSelectedDay('all');requestAnimationFrame(()=>document.getElementById('tour-days')?.scrollIntoView({behavior:'smooth',block:'start'}));}}/>}
 {tab==='route'&&<TourCountdown/>}
 {tab==='schedule'&&<section className="tour-schedule-intro"><div><p className="china-eyebrow">26 ОКТЯБРЯ — 2 НОЯБРЯ 2026</p><h1>Программа по дням</h1><p>Выберите дату: места, переезды, питание и подробности каждого дня.</p></div><div className="tour-schedule-photos">{['pandas','tianzi','lake'].map(id=><PlacePhoto key={id} place={places.find(p=>p.id===id)!}/>)}</div></section>}
 {(tab==='route'||tab==='schedule')&&<TourCalendar selectedDay={selectedDay} onDay={selectDay}/>}
 <TabsContent value="route"><Suspense fallback={<div className="china-section">Разворачиваем карту…</div>}><TourMap day={selectedDay} onDay={selectDay}/></Suspense><section className="china-section"><div className="china-section-heading"><p className="china-eyebrow">ПУТЬ ЧЕРЕЗ СЫЧУАНЬ И ХУНАНЬ</p><h2>Два города. Один большой мир.</h2></div><div className="china-city-grid"><article className="tour-city-card"><PlacePhoto place={places.find(p=>p.id==='alleys')!}/><div className="tour-city-copy"><span className="china-city-index">01 / 成都 · СЫЧУАНЬ</span><h3>Чэнду</h3><p>Панды и храмы, книжные лабиринты, хотпот и вечерняя Сычуаньская опера.</p><span className="tour-city-dates">26–28 октября · 1–2 ноября</span><button className="tour-city-link" onClick={()=>{setTab('schedule');setSelectedDay(1);requestAnimationFrame(()=>document.querySelector('.tour-schedule-intro')?.scrollIntoView({behavior:'smooth',block:'start'}));}}>К программе в Чэнду <ArrowRight size={17}/></button></div></article><article className="tour-city-card"><PlacePhoto place={places.find(p=>p.id==='tianzi')!}/><div className="tour-city-copy"><span className="china-city-index">02 / 张家界 · ХУНАНЬ</span><h3>Чжанцзяцзе</h3><p>Стеклянный мост, пещера Жёлтого дракона, озеро Баофэн и Небесные врата.</p><span className="tour-city-dates">28 октября — 1 ноября</span><button className="tour-city-link" onClick={()=>{setTab('schedule');setSelectedDay(4);requestAnimationFrame(()=>document.querySelector('.tour-schedule-intro')?.scrollIntoView({behavior:'smooth',block:'start'}));}}>К программе в Чжанцзяцзе <ArrowRight size={17}/></button></div></article></div></section><TourGallery onDay={day=>{setTab('schedule');setSelectedDay(day);requestAnimationFrame(()=>document.querySelector('.tour-schedule-intro')?.scrollIntoView({behavior:'smooth',block:'start'}));}}/></TabsContent>
 <TabsContent value="schedule"><section id="tour-days" className="china-section"><p className="china-disclaimer">Даты поездки: 26 октября — 2 ноября 2026. Вылет и возвращение — Шереметьево. Дни программы предварительно распределены с 26 октября по 2 ноября; привязку уточним после подтверждения времени прилёта. Время рейсов и поездов приведено из предложения туроператора и требует подтверждения.</p><div className="china-days">{(selectedDay==='all'||selectedDay==='departure'||selectedDay===1)&&<article className="china-day"><div className="china-day-number"><span>ОКТЯБРЬ</span><b>26</b></div><div><div className="china-day-meta"><span>Вылет в Китай</span></div><h2>Начало путешествия</h2><p>26 октября 2026 года · Шереметьево → Чэнду. Время вылета и аэропорт прибытия уточняются.</p></div></article>}{tour.days.filter(d=>selectedDay==='all'||selectedDay===d.day).map(d=><article className="china-day" key={d.day}><div className="china-day-number"><span>ДЕНЬ</span><b>{String(d.day).padStart(2,'0')}</b></div><div><div className="china-day-meta"><span>{tourDate(d.day)} 2026</span><span>{d.city}</span><span>{d.theme}</span></div><h2>{d.title}</h2><h3 className="tour-program-heading">Программа дня</h3><ul>{d.items.map(item=><li key={item}>{item}</li>)}</ul><p className="china-meals"><Utensils size={15}/>{d.meals}</p><DayPlaces day={d.day} onMap={()=>{setSelectedDay(d.day);setTab('route');requestAnimationFrame(()=>document.getElementById('tour-calendar')?.scrollIntoView({behavior:'smooth',block:'start'}));}}/></div></article>)}{(selectedDay==='all'||selectedDay==='return'||selectedDay===8)&&<article className="china-day"><div className="china-day-number"><span>НОЯБРЬ</span><b>02</b></div><div><div className="china-day-meta"><span>Возвращение в Москву</span></div><h2>Домой — с новыми историями</h2><p>2 ноября 2026 года · Чэнду → Шереметьево. Время и аэропорт вылета уточняются.</p></div></article>}</div></section></TabsContent>
 <TabsContent value="budget">{privateTour?(<section className="china-section"><p className="china-eyebrow">ПРЕДЛОЖЕНИЕ ТУРОПЕРАТОРА</p><h1 className="china-page-title">Путешествие в цифрах.</h1><p className="china-disclaimer">Цены из PDF, за одного человека. Оплата в рублях по курсу туроператора. Международный перелёт оплачивается отдельно. Общий итог поездки пока не известен.</p><div className="china-price-grid">{privateTour.prices.map(p=><article key={p.label}><p>{p.label}</p><strong>${p.amount.toLocaleString('ru-RU')}</strong><span>USD / человек</span></article>)}</div><h2 className="china-subtitle">Проживание и программа · оплачено</h2>{privateTour.tourPayment&&<div className="china-price-grid">{privateTour.tourPayment.travelers.map(name=><article key={name}><p>{name} · проживание и программа</p><strong>${privateTour.tourPayment!.perPerson.toLocaleString('ru-RU')}</strong><span>USD · оплачено</span></article>)}<article><p>Всего · Роман и Артур</p><strong>${privateTour.tourPayment.total.toLocaleString('ru-RU')}</strong><span>USD · оплачено за двоих</span></article></div>}<h2 className="china-subtitle">Наши авиабилеты</h2>{privateTour.flightCost?<div className="china-price-grid">{privateTour.flightCost.travelers.map(name=><article key={name}><p>{name} · туда и обратно</p><strong>{privateTour.flightCost!.perPerson.toLocaleString('ru-RU')} ₽</strong><span>Стоимость авиабилетов</span></article>)}<article><p>Всего · Роман и Артур</p><strong>{privateTour.flightCost.total.toLocaleString('ru-RU')} ₽</strong><span>Перелёт туда и обратно на двоих</span></article></div>:<p className="china-disclaimer">Стоимость авиабилетов уточняется.</p>}<div className="china-info-grid"><article><h2>Включено в тур</h2><ul>{tour.included.map(s=><li key={s}><Check size={16}/>{s}</li>)}</ul></article><article><h2>Дополнительно</h2><p>Международные авиаперелёты не включены.</p><p>Курс оплаты, условия отмены и личные расходы уточняются. Расходы на месте будем учитывать в юанях.</p></article></div><h2 className="china-subtitle">Отели из предложения</h2><div className="china-hotels">{tour.hotels.map(h=><p key={h}>{h}</p>)}</div><p className="china-disclaimer">Распределение отелей по ночам и бронирование не подтверждены.</p></section>):accessMessage}</TabsContent>
 <TabsContent value="checklist">{privateTour?(<section className="china-section"><p className="china-eyebrow">ДО НАЧАЛА ПУТЕШЕСТВИЯ</p><PackingList packing={privateTour.packing}/><h2 className="china-subtitle">Уточним главное.</h2><p className="china-disclaimer">Вопросы для завершения плана и подтверждения программы.</p><div className="china-questions">{privateTour.questions.map((q,i)=><article key={q}><span>{String(i+1).padStart(2,'0')}</span><p>{q}</p></article>)}</div></section>):accessMessage}</TabsContent>
 <TabsContent value="settings"><section className="china-section"><p className="china-eyebrow">ПЛАН ПОД РУКОЙ</p><h1 className="china-page-title">Наше путешествие, наш темп.</h1><p className="china-disclaimer">От семьи едут Роман и Артур, вместе со школьным классом Артура. Поездка — с 26 октября по 2 ноября 2026, вылет и возвращение в Шереметьево. Карта и фотографии уже доступны; календарные даты экскурсий, личные заметки и расходы дополним после подтверждения программы. Личные правки сохраняются в этом браузере.</p><div className="china-info-grid"><article><h2>Резервная копия</h2><p>Сохраните основу календарного плана для дальнейшего заполнения.</p><button className="secondary" onClick={exportBackup}><Download size={17}/>Сохранить план</button></article><article><h2>Импорт маршрута</h2><label>Файл маршрута JSON<input type="file" accept=".json,application/json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>2000000){onImport('');return;}onImport(await f.text());e.target.value='';}}/></label></article></div>{message&&<p className="notice" role="status">{message}</p>}</section></TabsContent>
 </Tabs><footer><Compass size={20}/><span>Китай 2026 · Наше путешествие</span><span>made with ♥ by Roman A. Proskurnin</span></footer></main>;
}
